name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
    - env:
        PSGALLERY_DEPLOY_KEY: ${{ secrets.PSGALLERY_DEPLOY_KEY }}
      run: |
        $ModuleName = "OfficeAddinManager"
        $ModuleFolderPath = $env:PSModulePath.Split(";") | select -first 1
        $ModuleFolderToPublish = Join-path $ModuleFolderPath $ModuleName 
        New-Item $ModuleFolderToPublish -ItemType Directory -Force
        Copy-Item @(".\$ModuleName.psm1",".\$ModuleName.psd1") -Destination $ModuleFolderToPublish
        Publish-Module -Name $ModuleName -NuGetApiKey $env:PSGALLERY_DEPLOY_KEY -Repository PSGallery
        Remove-Item $ModuleFolderToPublish -Force

